### ISSUE TITLE
Missing "pg_catalog.pg_tables" and "information_schema.tables"

### ISSUE THREAD

**Issue by simonw** [electric-sql/pglite#8]
I tried running this SQL query:
```sql
select * from pg_catalog.pg_tables
```
But I got this error:
> `RuntimeError: relation "pg_catalog.pg_tables" does not exist at character 15`

Is there a way to do this at the moment? If not, could there be?

**Comment by kiwicopple** [comment]
Interesting - most of the catalog tables are there, but not this one ([src](https://kiwicopple.github.io/postgres.run/catalog.html) )

Could be due to the way the underlying [fork](https://github.com/electric-sql/postgres-wasm) handles the storage?

<details>
  <summary>Full list of catalog</summary>

<img width="592" alt="image" src="https://github.com/electric-sql/pglite/assets/10214025/5975d763-03cc-4140-a073-1b79bbc055f5">


</details>

**Comment by simonw** [comment]
Huh, yead - `select * from pg_catalog.pg_type` works for me.

**Comment by simonw** [comment]
I've been playing around with this in an Observable Framework notebook here: https://simonw.github.io/observable-framework-experiments/postgresql

Source code here: https://github.com/simonw/observable-framework-experiments/blob/main/docs/postgresql.md?plain=1

**Comment by samwillis** [comment]
I believe this is due to the simplified [initdb.ts](https://github.com/electric-sql/pglite/blob/main/packages/pglite/src/initdb.ts) that replaces the conventional `initdb` command that comes with Postgres. It's not fully creating all the catalog tables.

We should look at compiling [`initdb`](https://github.com/electric-sql/postgres-wasm/blob/3443047567d17ba34138875aca4a56f0a2fa5f18/src/bin/initdb/initdb.c) to wasm, although it runs `postgres --boot` which we would need to do separately which creates a little complexity.

**Comment by samwillis** [comment]
The missing "pg_catalog.pg_tables" and "information_schema.tables" (among others) are fixed in #41 and we plan to do a release early next week after a few finals checks.

If anyone wants to take it for a spin, there is dev build linked in PR #48 which is the tip of a stack of PRs.
